# Generated by Django 5.1.7 on 2025-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
            ],
        ),
    ]
