# Generated by Django 5.1.7 on 2025-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_edge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='edge_id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='node_id',
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
