# Generated by Django 5.1.7 on 2025-03-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_edge_edge_id_remove_node_node_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='id',
            new_name='edge_id',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='id',
            new_name='node_id',
        ),
    ]
